// Lasertag Event System Defines

// Kit HP values
#define LASERTAG_KIT_DEFAULT_HP 3
#define LASERTAG_KIT_COMMANDER_HP 5
#define LASERTAG_KIT_SCOUT_HP 2
#define LASERTAG_KIT_ENGINEER_HP 2

// Weapon values
#define LASERTAG_BLASTER_MAGAZINE_SIZE 15
#define LASERTAG_PISTOL_MAGAZINE_SIZE 8
#define LASERTAG_BLASTER_RELOAD_TIME (3 SECONDS)
#define LASERTAG_PISTOL_RELOAD_TIME (5 SECONDS)

// Damage values (to kit HP, not mob)
#define LASERTAG_DAMAGE_CHEST 1
#define LASERTAG_DAMAGE_HEAD 2

// Scoring values
#define LASERTAG_SCORE_HEADSHOT 500
#define LASERTAG_SCORE_BODYSHOT 200
#define LASERTAG_SCORE_DEATH -100
#define LASERTAG_SCORE_CONTROLPOINT_PER_SECOND 50

// Game mode defaults
#define LASERTAG_DEFAULT_TIMER (5 MINUTES)
#define LASERTAG_DEFAULT_RESPAWNS -1 // -1 = infinite

// Respawn protection
#define LASERTAG_RESPAWN_SAFE_RADIUS 3

// Commander buff
#define LASERTAG_COMMANDER_BUFF_RADIUS 7
#define LASERTAG_COMMANDER_SPEED_BOOST 1.2
