// Lasertag Event System - Game Mode Enum

#define LASERTAG_MODE_NONE 0
#define LASERTAG_MODE_TEAM_DEATHMATCH 1
#define LASERTAG_MODE_CONTROL_POINT 2
#define LASERTAG_MODE_ATTACK 3
#define LASERTAG_MODE_FREE_FOR_ALL 4
#define LASERTAG_MODE_SHADOW_REALM 5
